### ISSUE TITLE
Output as individual spectra files.

### ISSUE THREAD

**Issue by oolonek** [bjonnh-virtuous/pylibmassfiles#3]
The possibility to output individual spectra file if needed would be nice.

**Comment by bjonnh-virtuous** [comment]
How so?

**Comment by oolonek** [comment]
Having a the possibility to output an individual .mat file per compound instead of a unique .mat with all compounds.

**Comment by bjonnh-virtuous** [comment]
That would unnecessarily bloat the program. You can split with: 
awk -v RS="\n\n" 'BEGIN {n=1}{print $0 > "splitted_"n++".mat"}' mattosplit.mat

If we want to do that in the program, we would have to add a lot of commands (how to number the files etc).
